packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  2204_http_directory = "ubuntu/config2204"
  2204_iso_filename  = "local:isostorage/ubuntu-22.04.5-live-server-amd64.iso"
  2204_iso_checksum  = "9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0" #pragma: allowlist secret
  2204_proxmox_vmid  = "900"
  2204_template_des  = "Ubuntu 22.04.5 x86_64 template generated by Packer on ${timestamp()}. Username: proxmox"
  2204_template_name = "tpl-ubuntu-2204"

  2404_http_directory = "ubuntu/config2404"
  2404_iso_filename  = "local:isostorage/ubuntu-24.04.1-live-server-amd64.iso"
  2404_iso_checksum  = "e240e4b801f7bb68c20d1356b60968ad0c33a41d00d828e74ceb3364a0317be9" #pragma: allowlist secret
  2404_proxmox_vmid  = "901"
  2404_template_des  = "Ubuntu 24.04.1 x86_64 template generated by Packer on ${timestamp()}. Username: proxmox"
  2204_template_name = "tpl-ubuntu-2404"

  vm_os = "l26"
}

source "proxmox-iso" "ubuntu-2204" {
  boot_command            = ["c", "linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ", "<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>"]
  boot_wait               = "10s"
  cloud_init              = true
  cloud_init_storage_pool = "${var.vm_storage_pool}"
  cores                   = "${var.vm_cores}"
  cpu_type                = "${var.vm_cpu_type}"
  disks {
    disk_size         = "${var.vm_disk_size}"
    format            = "${var.vm_disk_format}"
    storage_pool      = "${var.vm_storage_pool}"
    type              = "${var.vm_disk_type}"
  }
  http_directory           = "${local.2204_http_directory}"
  insecure_skip_tls_verify = true
  iso_checksum             = "${local.2204_iso_checksum}"
  iso_file                 = "${local.2204_iso_filename}"
  memory                   = "${var.vm_memory}"
  network_adapters {
    bridge = "${var.vm_network_adapter_bridge}"
    model  = "${var.vm_network_adapter_model}"
  }
  node                 = "${var.proxmox_node}"
  os                   = "${local.vm_os}"
  proxmox_url          = "${var.proxmox_api_url}"
  qemu_agent           = "${var.vm_enable_qemu_agent}"
  scsi_controller      = "${var.vm_scsi_controller}"
  sockets              = "${var.vm_sockets}"
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "20m"
  ssh_username         = "${var.ssh_username}"
  template_description = "${local.2204_template_des}"
  template_name        = "${local.2204_template_name}"
  token                = "${var.proxmox_token}"
  unmount_iso          = true
  username             = "${var.proxmox_user}"
  vm_id                = "${local.2204_proxmox_vmid}"
}

source "proxmox-iso" "ubuntu-2404" {
  boot_command            = ["c", "linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ", "<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>"]
  boot_wait               = "10s"
  cloud_init              = true
  cloud_init_storage_pool = "${var.vm_storage_pool}"
  cores                   = "${var.vm_cores}"
  cpu_type                = "${var.vm_cpu_type}"
  disks {
    disk_size         = "${var.vm_disk_size}"
    format            = "${var.vm_disk_format}"
    storage_pool      = "${var.vm_storage_pool}"
    type              = "${var.vm_disk_type}"
  }
  http_directory           = "${local.2404_http_directory}"
  insecure_skip_tls_verify = true
  iso_checksum             = "${local.2404_iso_checksum}"
  iso_file                 = "${local.2404_iso_filename}"
  memory                   = "${var.vm_memory}"
  network_adapters {
    bridge = "${var.vm_network_adapter_bridge}"
    model  = "${var.vm_network_adapter_model}"
  }
  node                 = "${var.proxmox_node}"
  os                   = "${local.vm_os}"
  proxmox_url          = "${var.proxmox_api_url}"
  qemu_agent           = "${var.vm_enable_qemu_agent}"
  scsi_controller      = "${var.vm_scsi_controller}"
  sockets              = "${var.vm_sockets}"
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "20m"
  ssh_username         = "${var.ssh_username}"
  template_description = "${local.2404_template_des}"
  template_name        = "${local.2404_template_name}"
  token                = "${var.proxmox_token}"
  unmount_iso          = true
  username             = "${var.proxmox_user}"
  vm_id                = "${local.2404_proxmox_vmid}"
}

build {
  
  source "source.proxmox-iso.ubuntu-2204" {
    description   = "Ubuntu 22.04 Proxmox template (packer generated)"
    name          = "homelab-ubuntu-2204"
    template_name = "${local.2204_template_name}"
  }

  source "source.proxmox-iso.ubuntu-2404" {
    description   = "Ubuntu 24.04 Proxmox template (packer generated)"
    name          = "homelab-ubuntu-2404"
    template_name = "${local.2404_template_name}"
  }

  provisioner "shell" {
    inline = ["while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"]
  }

  provisioner "shell" {
    inline = [
      "sudo rm -f /etc/cloud/cloud.cfg.d/99-installer.cfg",
      "sudo rm -f /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg",
      "sudo cloud-init clean"
    ]
  }

  provisioner "shell" {
    environment_vars = [
      "TEMPLATE=${source.template_name}"
    ]
    inline = [
      "echo $(date +%Y%m%d-%H%M%S)-$TEMPLATE > /home/proxmox/packer.build"
    ]
  }

  provisioner "file" {
    source = "ubuntu/scripts/hardening.sh"
    destination = "~/packer-hardening.sh"
  }

  provisioner "shell" {
    inline = [
      "sudo bash ~/packer-hardening.sh"
    ]
  }

  provisioner "shell" {
    environment_vars = [
      "CHEF_LICENSE=accept-silent"
    ]
    inline = [
      "curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec",
      "cd ~",
      "git clone https://github.com/dev-sec/linux-baseline.git",
      "inspec exec linux-baseline --reporter=cli json:packer_$(hostname)_$(date +%Y%m%d_%H%M%S)_inspec.json"
    ]
    valid_exit_codes = [ 0, 100]
  }
}